### ISSUE TITLE
Does not encode when used with Readline

### ISSUE THREAD

**Issue by Derbeth** [ashtuchkin/iconv-lite#117]
`encodeStream()` is NO-OP when used in [Node Readline](https://nodejs.org/dist/latest-v4.x/docs/api/readline.html). To reproduce:

fail.js:

```
'use strict';

const fs = require('fs'),
    iconv = require('iconv-lite'),
    readline = require('readline');

const writeStream = iconv.encodeStream('win1250')
    .collect(function() {throw new Error('Check I am called')})
    .pipe(fs.createWriteStream('out-win1250.txt'));
const rl = readline.createInterface({
    input: fs.createReadStream('in-utf8.txt'),
    output: writeStream,
    terminal: false
});
rl.on('line', function(line) {
    writeStream.write(line);
    writeStream.write("\n");
});
rl.on('close', function() {
    writeStream.end();
    rl.close();
});
fs.createReadStream('in-utf8.txt')
    .pipe(iconv.decodeStream('utf8'))
    .pipe(iconv.encodeStream('win1250'))
    .pipe(fs.createWriteStream('out-win1250-no-readline.txt'));
```

in-utf8.txt:

```
żółcią
```

Run `node fail.js` and compare `out-win1250-no-readline.txt` and `out-win1250.txt`. The second file is the input with no encoding change.

Actually, `fail.js` should not finish - it should be killed by an exception thrown from `collect` callback.

**Comment by ashtuchkin** [comment]
Sorry for the huge delay.

So what happens here is `writeStream` is the file write stream created by `fs.createWriteStream('out-win1250.txt')`, not encoding stream. This is because the `pipe()` method returns it's argument and not `this`. To make it work, you need to get the correct writeStream:
```
const writeStream = iconv.encodeStream('win1250');
writeStream.pipe(fs.createWriteStream('out-win1250.txt'));
```

Also, it's not recommended to use `.collect()` method together with piping data to another stream - the backpressure mechanisms will probably screw up. Only use `.collect()` at the end of the pipe.
