### ISSUE TITLE
How to use in the react-native ?

### ISSUE THREAD

**Issue by AdamChrist** [ashtuchkin/iconv-lite#148]
I want to use iconv-lite in react-native, but icon-lite require stream of Node's stream.
The error message is "Unable to resolve module stream".
Is there any way I can use it in react-native? thanks

**Comment by ashtuchkin** [comment]
That's a very good question. Although it seems react-native is not a full
node environment as it doesn't know streams or Buffer class, we still want
to support it because it's in this project's mission to support all js
environments.

I'll look into making it trivially usable by switching to Uint8Array
instead of Buffer if the latter is not available. No promises on timeline,
though.

Meanwhile for now you can try to build it into a single .js file using
browserify, then use the resulting file like in a browser.

Alex.

--
Alexander Shtuchkin

**Comment by AdamChrist** [comment]
@ashtuchkin thanks

**Comment by ashtuchkin** [comment]
Tracking React Native support in #150.
