### ISSUE TITLE
Can't restore the original string after conversion

### ISSUE THREAD

**Issue by ericmorand** [ashtuchkin/iconv-lite#175]
Consider the following function:

```typescript
import * as iconvLite from "iconv-lite";

export function iconv(inCharset: string, outCharset: string, str: string): string {
    let buffer: Buffer = new Buffer(str);

    str = iconvLite.decode(buffer, inCharset);
    buffer = iconvLite.encode(str, outCharset) as Buffer;

    return buffer.toString();
}
```

When I'm calling it with `iconv('UTF-8', 'ISO-8859-1', 'Äé')`, I get successfully '��';

But when I do` iconv('ISO-8859-1', 'UTF-8', '��')`, I don't get 'Äé' back. Instead I get some garbage 'ï¿½ï¿½'

Am I doing something wrong? And if so how can I use iconv-lite to convert without being destructive?

**Comment by ashtuchkin** [comment]
Hey Eric, it looks like you're doing 4 conversions in your iconv function instead of one:
```
export function iconv(inCharset: string, outCharset: string, str: string): string {
    let buffer: Buffer = new Buffer(str);  // <-- this is the first one. It converts str to buffer using utf8 encoding.

    str = iconvLite.decode(buffer, inCharset);  // <-- this is the second 
    buffer = iconvLite.encode(str, outCharset) as Buffer;  // <-- this is the third

    return buffer.toString();  // <-- this is the fourth, converting buffer to string, using utf8 encoding.
}
```

When you're working with encoded strings, I really recommend using buffers for encoded data and convert them to strings when you need to display them or do some other work. Otherwise, it's easy to be confused with all the implicit conversions Node.js does for you. See also https://github.com/ashtuchkin/iconv-lite/wiki.

If you can't work with buffers directly, you can treat strings as binary-encoded buffers. In that case, when you convert to/from real buffers, use "binary" as the encoding (see https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings):
```
let buffer: Buffer = new Buffer(str, "binary");
let str = buffer.toString("binary");
```

One problem with that approach is, given you example, `'Äé'` is not a valid utf-8 encoded string. To get a utf-8 encoded string, you should - you guessed it correctly - encode it first, *before* passing to your `iconv` function. Two options are `new Buffer(str).toString("binary")`, or `iconvLite.decode(iconvLite.encode(str, "utf8"), "binary")`.

Lastly, '�' character means that bytes or characters are not representable in the encoding you want. Almost all encodings are destructive by their nature (utf8, utf16 etc being the exception), so you'll need to handle this in your code.

Let me know if you need more info.

**Comment by ericmorand** [comment]
@ashtuchkin, thanks for that great answer. I think there are too much void in my understandings of charsets to fully understand it and I now have to humbly go and read some resources about it. ^^

Anyway, thanks.
