### ISSUE TITLE
Question about decoding and encoding in single step

### ISSUE THREAD

**Issue by igorthy** [ashtuchkin/iconv-lite#244]
Hi,

I use streaming support within library like this:
```
fs.createReadStream(file)
.pipe(iconv.decodeStream('win1255'))
.pipe(iconv.encodeStream('utf8'))
...
```

Is it possible to use single pipe? (I know I can use **through** module to create such transform stream but it is still 2 separate streams behind it)
Something like this:
```
fs.createReadStream(file)
.pipe(iconv.decodeEncodeStream('win1255', 'utf8'))
...
```
Thanks

**Comment by ashtuchkin** [comment]
Currently there's no interface to do that. Moreover, internally it'll still
be 2 operations (decoding, then encoding) due to how the library is
structured.

What are you piping this into? If it's a file or network socket, you can
likely skip the encodeStream("utf8") as it'll be done automatically by
Node.js.

**Comment by igorthy** [comment]
I'm  writing it to file (converting file with custom format to CSV formatted text file)
It is probably something I don't know about decoding/encoding but the reason I asked this question is because I assumed that when decoding text it is being decoded to some intermediate representation (Unicode?)
Then the encode step converts this intermediate representation to utf8 (in my case).
So I was thinking that it could be more efficient to decode the stream to utf8 right away.
So the entire operation is done in single pass.

**Comment by ashtuchkin** [comment]
I see. You're right, it's decoded to an intermediate representation, which
is JS strings (which are internally utf16), then encode converts it to
utf8. It might be more efficient to convert it to utf8 directly, but in
that case I'd need to implement N^2 codecs (every input x every output
matrix), which is not feasible. In practice, all conversion libraries use
some kind of intermediate representation internally, even if they don't
expose it to the client. In iconv-lite the internal representation is
exposed because it's convenient to use directly in a lot of cases.

With pipelines, the conversion is still happening in a single pass (i.e.
it's not reading everything into memory at any stage), even if there are 2
transformations (encode and decode), so memory-wise it should be ok.

That being said, if you don't like seeing two transformations here,
skipping encoding part should work (node.js is converting strings to utf8
by default):
```
fs.createReadStream(...).pipe(iconv.decodeStream("win1255")).pipe(fs.createWriteStream(outfile))
```

--
Alexander Shtuchkin

**Comment by igorthy** [comment]
Ok, got it.
Thank you!
